### ISSUE TITLE
Required module msvcrt only available on Windows

### ISSUE THREAD

**Issue by btroller** [TraceRainbolt/LC3-Simulator#1]
The msvcrt is only available for Windows, so the simulator won't run on other OSs yet. We could change it to something like [curses](https://docs.python.org/2.7/library/curses.html) ([as suggested here](http://stackoverflow.com/questions/8718561/python-3-how-to-input-data-without-pressing-return-in-osx)), or make a branch/branches for other OSs using other modules.

Basically, I can't run it, which makes me sad.

**Comment by TraceRainbolt** [comment]
If we can get it working on all platforms with only one module that'd be good, although honestly it's only in there so I can get the traps to work in command line. Once we get to the UI I'll probably use something like PyGame to make a console window that handles the key detection. Either way, if you could get key detection working on Mac for now that's all that's necessary.

**Comment by TraceRainbolt** [comment]
The input is no longer dependent on a windows only import.
